from flask import Flask, send_file
import subprocess
import os

app = Flask(__name__)


@app.route('/')
def home():
    # Run the sin_graph.py file using subprocess
    subprocess.run(['python3', 'sin_graph.py'], check=True)

    # Assuming the script generates a plot and saves it as 'sine_wave.png' in the same directory
    image_path = 'sine_wave.png'

    # Check if the image file was generated and send it as a response
    if os.path.exists(image_path):
        return '''
            <h1>Sin Graph Generated:</h1>
            <img src="/graph">
        '''
    else:
        return "<h1>Error: Image not found</h1>"


@app.route('/graph')
def graph():
    # Serve the image file that was generated by sin_graph.py
    return send_file('sine_wave.png', mimetype='image/png')


if __name__ == "__main__":
    app.run()
